# Generated by Django 5.0.6 on 2024-05-29 10:29

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_unique_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('bin_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10)),
                ('manufacture_date', models.DateField(auto_now_add=True)),
                ('is_bin_asigned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['bin_unique_id'],
            },
        ),
        migrations.CreateModel(
            name='BinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_level', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('bin_temperaure', models.CharField(max_length=20)),
                ('bin_orientation', models.CharField(max_length=20)),
                ('battery_level', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('the_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_bin', to='bin_api.bin')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('bin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bin_id', to='bin_api.bin')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100)),
                ('street', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='bin_api.user')),
            ],
        ),
    ]
