# Generated by Django 5.0.1 on 2024-01-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bindata',
            name='binOrientation',
        ),
        migrations.AddField(
            model_name='bindata',
            name='batteryLevel',
            field=models.CharField(default=56, max_length=10),
            preserve_default=False,
        ),
    ]
