# Generated by Django 5.0.1 on 2024-01-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_api', '0002_remove_bindata_binorientation_bindata_batterylevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindata',
            name='binOrientation',
            field=models.CharField(default='Fallen', max_length=20),
            preserve_default=False,
        ),
    ]
